# Default

## Plugin manager
## https://github.com/Shougo/dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'
## Asynchronous execution for vim
## https://github.com/Shougo/vimproc.vim
[[plugins]]
repo = 'Shougo/vimproc.vim'

## Remote plugin framework without ":UpdateRemotePlugins"
## https://github.com/roxma/nvim-yarp
[[plugins]]
repo = 'roxma/nvim-yarp'

## neovim rpc client working on vim8 dependent on nvim-yarp
## https://github.com/roxma/vim-hug-neovim-rpc
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

#------------------------------------------------------------------- 

# View

## Statusline/tabline
## https://github.com/itchyny/lightline.vim
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\'colorscheme'  :'one',
		\'active'   :   {
		\	'left'	:	[	['mode', 'paste'],
		\							['readonly', 'filename', 'modified', 'ale']	]
		\},
		\'component_function'	:	{
		\	'ale'	:	'ALEGetStatusLine'
		\}
		\}
'''

## Color scheme
## https://github.com/w0ng/vim-hybrid
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
'''

#------------------------------------------------------------------- 

# Utility

## File system explorer
## https://github.com/scrooloose/nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden=1
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

## Source code browser
## https://github.com/vim-scripts/taglist.vim
[[plugins]]
repo = 'vim-scripts/taglist.vim'
hook_add = '''
  let Tlist_Use_Right_Window = 1
  nnoremap <silent> <leader>t :TlistOpen<CR>
'''

#------------------------------------------------------------------- 

# Completion

## User inputs
## https://github.com/Shougo/neco-syntax
[[plugins]]
repo = 'Shougo/neco-syntax'

## English
## https://github.com/ujihisa/neco-look
[[plugins]]
repo = 'ujihisa/neco-look'

## Extensible and asynchronous completion framework
## https://github.com/Shougo/deoplete.nvim
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
    call deoplete#enable()
    " No display of the number of competion list
    set shortmess+=c
    " <TAB>: completion.
    inoremap <silent><expr> <TAB>
          \ pumvisible() ? "\<C-n>" :
          \ <SID>check_back_space() ? "\<TAB>" :
          \ deoplete#manual_complete()
    function! s:check_back_space() abort
      let col = col('.') - 1
      return !col || getline('')[col - 1]  =~ '\s'
    endfunction
    " <S-TAB>: completion back.
    inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"
    " <C-e>: popup cancel
    inoremap <expr><C-e>       deoplete#cancel_popup()
    call deoplete#custom#source('_', 'matchers', ['matcher_head'])
    call deoplete#custom#source('_', 'converters', [
          \ 'converter_remove_paren',
          \ 'converter_remove_overlap',
          \ 'matcher_length',
          \ 'converter_truncate_abbr',
          \ 'converter_truncate_menu',
          \ 'converter_auto_delimiter',
          \ ])
    call deoplete#custom#option('keyword_patterns', {
          \ '_': '[a-zA-Z_]\k*\(?',
          \ 'tex': '[^\w|\s][a-zA-Z_]\w*',
          \ })
    call deoplete#custom#option('camel_case', v:true)
'''
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    set completeopt-=preview
'''
