# Default
## Plugin manager
## https://github.com/Shougo/dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'
## Asynchronous execution for vim
## https://github.com/Shougo/vimproc.vim
[[plugins]]
repo = 'Shougo/vimproc.vim'

## Remote plugin framework without ":UpdateRemotePlugins"
## https://github.com/roxma/nvim-yarp
[[plugins]]
repo = 'roxma/nvim-yarp'

## neovim rpc client working on vim8 dependent on nvim-yarp
## https://github.com/roxma/vim-hug-neovim-rpc
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

#------------------------------------------------------------------- 

# View

## Statusline/tabline
## https://github.com/itchyny/lightline.vim
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\'colorscheme'  :'one',
		\'active'   :   {
		\	'left'	:	[	['mode', 'paste'],
		\							['readonly', 'filename', 'modified', 'ale']	]
		\},
		\'component_function'	:	{
		\	'ale'	:	'ALEGetStatusLine'
		\}
		\}
'''

## Color scheme
## https://github.com/w0ng/vim-hybrid
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
'''

#------------------------------------------------------------------- 

# Utility

## File system explorer
## https://github.com/scrooloose/nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden=1
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

## Windows resizer
## https://github.com/simeji/winresizer
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_start_key = '<C-b>'
'''

## Source code browser
## https://github.com/vim-scripts/taglist.vim
[[plugins]]
repo = 'vim-scripts/taglist.vim'
hook_add = '''
  let Tlist_Use_Right_Window = 1
  nnoremap <silent> <leader>t :TlistOpen<CR>
'''

#------------------------------------------------------------------- 

# Completion

## User inputs
## https://github.com/Shougo/neco-syntax
[[plugins]]
repo = 'Shougo/neco-syntax'

## English
## https://github.com/ujihisa/neco-look
[[plugins]]
repo = 'ujihisa/neco-look'


## ddc
[[plugins]]
repo = 'Shougo/ddc.vim'
